name: users_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  date_time_picker: ^2.1.0
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_easyloading: ^3.0.5
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.4
  flutter_riverpod: ^2.4.4
  flutter_staggered_grid_view: ^0.7.0
  formz: ^0.6.1
  get_it: ^7.6.4
  go_router: ^12.0.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  shimmer_animation: ^2.1.0+1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:

    - assets/icons/
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/logo.png
  color_dark: "#121212"
  image_dark: assets/icons/logo.png

  android_12:
    image: assets/icons/logo-12.png
    icon_background_color: "#ffffff"
    image_dark: assets/icons/logo-12.png
    icon_background_color_dark: "#121212"

  web: false
