name: users_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  date_time_picker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_riverpod: ^2.4.4
  formz: ^0.6.1
  get_it: ^7.6.4
  go_router: ^12.0.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
